version: '3.8'

services:
  queue-db:
    env_file: .env
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_NAME}
    ports:
      - ${DB_PORT}:27017
    restart: always
    volumes:
      - queue_volume:/data/db
    networks:
      - queue-net
    healthcheck:
      test: ['CMD', 'mongosh', '--eval', "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  queue-server:
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    environment:
      DB_HOST: queue-db
      DB_URL: mongodb://${DB_USER}:${DB_PASSWORD}@queue-db:${DB_PORT}/${DB_NAME}?authSource=admin
    depends_on:
      queue-db:
        condition: service_healthy
    networks:
      - queue-net

networks:
  queue-net:
    driver: bridge

volumes:
  queue_volume:
